version: build{build}
image: Visual Studio 2015

branches:
  only:
    - appveyor

platform:
  - x86
  - x64

install:
  - cmd: echo Running build
  - cmd: set MINGW-W64_BASE=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0
  - cmd: set PATH=%MINGW-W64_BASE%\mingw32\bin;C:\msys64\usr\bin;%PATH%
  - cmd: echo %Platform%
  - cmd: uname -a
  - cmd: pacman --noconfirm -S mingw32/mingw-w64-i686-cppunit
  - cmd: find C:\mingw-w64 -name "*cppunit*"
  - cmd: find C:\msys64 -name "*cppunit*"
  - cmd: python -x %cd%\waf configure --interval-lib=filib
  - cmd: python -x %cd%\waf build install clean

build_script:
  - cmd: echo Running install
  #- cmd: python -x %cd%\waf utest

on_finish:
  - cmd: cat C:\projects\ibex-lib\__build__\config.log
