version: build{build}
image: Visual Studio 2015

branches:
  only:
    - appveyor

platform:
  - x86
  - x64

install:
  - cmd: echo %Platform%
  - cmd: set MINGW-W64_BASE=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0
  - cmd: set PATH=%MINGW-W64_BASE%\mingw32\bin;C:\msys64\usr\bin;%PATH%
  - cmd: uname -a
  - cmd: pacman --noconfirm -S mingw32/mingw-w64-i686-cppunit
  - cmd: set CPATH=%CPATH%;C:\msys64\mingw32\include
  - cmd: set LIBRARY_PATH=%LIBRARY_PATH%;C:\msys64\mingw32\lib
  - cmd: echo %PATH%
  - cmd: echo %CPATH%
  - cmd: echo %LIBRARY_PATH%

build_script:
  - cmd: python -x %cd%\waf configure --interval-lib=filib --prefix=%HOMEDRIVE%%HOMEPATH%
  - cmd: python -x %cd%\waf build install clean
  #- cmd: cat __build__/c4che/_cache.py

test_script:
  - cmd: python -x %cd%\waf -vvv utest

#on_failure:
on_finish:
  - cmd: cat C:\projects\ibex-lib\__build__\config.log
