version: build{build}
image: Visual Studio 2015

platform:
  - x86

environment:
  matrix:
    - TEST_INTERVAL_LIB: "gaol"
    - TEST_INTERVAL_LIB: "filib"

install:
  - cmd: echo %Platform%
  - cmd: set MINGW=C:\MinGW
  - cmd: set MSYS=%MINGW%\msys\1.0
  - cmd: set PATH=%MINGW%\bin;%MSYS%\bin;%PATH%
  - cmd: uname -a
  - cmd: find C:\MinGW -name "*cppunit*"
  - cmd: find C:\MinGW -name "mingw-get"
  - cmd: C:\MinGW\msys\1.0\bin\sh.exe -c "mingw-get update"
  - cmd: ls -l C:\MinGW\var\lib\
  - cmd: ls -l C:\MinGW\var\lib\mingw-get\
  - cmd: ls -l C:\MinGW\var\lib\mingw-get\data\
  - cmd: grep "cppunit" C:\MinGW\var\lib\mingw-get\data\*.xml
  - cmd: C:\MinGW\msys\1.0\bin\sh.exe -c 'grep "cppunit" /mingw/var/lib/mingw-get/data/*.xml'
  - cmd: C:\MinGW\msys\1.0\bin\sh.exe -c "./waf configure build install "
  - cmd: pacman --noconfirm -S mingw32/mingw-w64-i686-cppunit
  - cmd: set CPATH=%CPATH%;C:\msys64\mingw32\include
  - cmd: set LIBRARY_PATH=%LIBRARY_PATH%;C:\msys64\mingw32\lib
  - cmd: set PREFIX=%HOMEDRIVE%%HOMEPATH%

build_script:
  - cmd: python -x %cd%\waf configure --interval-lib=%TEST_INTERVAL_LIB% --prefix=%PREFIX%
  - cmd: python -x %cd%\waf build install clean

test_script:
  - cmd: set PKG_CONFIG_PATH=%PREFIX%\share\pkgconfig
  # We need to add the path to libcppunit in PATH
  - cmd: set PATH=%PATH%;C:\msys64\mingw32\bin
  - cmd: python -x %cd%\waf utest

on_failure:
  - cmd: cat C:\projects\ibex-lib\__build__\config.log
  - cmd: cat C:\projects\ibex-lib\__build__\utest_config.log
  - cmd: cat C:\projects\ibex-lib\__build__\utest_run.log
