version: build{build}
image: Visual Studio 2015

platform:
  - x86

environment:
  matrix:
    - TEST_INTERVAL_LIB: "gaol"
    - TEST_INTERVAL_LIB: "filib"

install:
  - cmd: set MINGW=C:\MinGW
  - cmd: set MSYS=%MINGW%\msys\1.0
  - cmd: set PATH=%MSYS%;%MSYS%\bin;%MSYS%\lib;%PATH%
  - cmd: set PATH=%MINGW%;%MINGW%\bin;%MINGW%\lib;%PATH%
  - cmd: set PREFIX=%HOMEDRIVE%%HOMEPATH%
  # print some info
  - cmd: uname -a
  - cmd: echo %Platform%
  - cmd: sh.exe -c "echo $TEST_INTERVAL_LIB"
  # install cppunit library from source
  - cmd: sh.exe -c "wget http://dev-www.libreoffice.org/src/cppunit-1.13.2.tar.gz"
  - cmd: sh.exe -c "tar -xzf cppunit-1.13.2.tar.gz"
  - cmd: sh.exe -c "cd cppunit-1.13.2 && ./configure && make && make install"
  # Set PKG_CONFIG_PATH to install directories of Ibex and cppunit
  - cmd: set PKG_CONFIG_PATH=%PREFIX%\share\pkgconfig;%MSYS%\local\lib\pkgconfig
  # Add the directory of pkg-config in PATH
  - cmd: set PATH=%PATH%;C:\msys64\mingw32\bin
  - cmd: sh.exe -c "g++ -o test.exe test.cpp"
  - cmd: sh.exe -c "./test.exe"
  - cmd: objdump -p test.exe

build_script:
  - cmd: sh.exe -c "./waf configure --interval-lib=$TEST_INTERVAL_LIB --prefix=$PREFIX"
  - cmd: sh.exe -c "./waf build install clean"

test_script:
  - cmd: set PATH=%PATH%;%MSYS%\local\lib;%MSYS%\local\bin
  - cmd: set PATH=%PATH%;%PREFIX%\lib;%PREFIX%\lib\ibex\3rd
  - cmd: echo %PATH%
  - cmd: sh.exe -c "echo $PATH"
  - cmd: sh.exe -c "./waf utest"

on_failure:
  - cmd: find %MINGW% -name "libgcc_s_dw2-1.dll"
  - cmd: find %MINGW% -name "libstdc++-6.dll"
  - cmd: find %MINGW% -name "libcppunit-1-13-0.dll"
  - cmd: ls -l __build__\tests\utest_Arith.exe
  - cmd: objdump -p __build__\tests\utest_Arith.exe | grep -i dll
  - cmd: objdump -p C:\MinGW\bin\gcc.exe | grep -i dll
  - cmd: objdump -p C:\MinGW\msys\1.0\bin\make.exe | grep -i dll
  - cmd: ls -l C:\MinGW\libexec
  - cmd: ls -l C:\MinGW\mingw32
  - cmd: ls -l C:\MinGW\share
  - cmd: sh.exe -c "./__build__/tests/utest_Arith"
  - cmd: cat C:\projects\ibex-lib\__build__\config.log
  - cmd: cat C:\projects\ibex-lib\__build__\utest_config.log
  - cmd: cat C:\projects\ibex-lib\__build__\utest_run.log
