version: build{build}
image: Visual Studio 2015

platform:
  - x86

environment:
  matrix:
    - TEST_INTERVAL_LIB: "gaol"
    - TEST_INTERVAL_LIB: "filib"

install:
  - cmd: set MINGW=C:\MinGW
  - cmd: set MSYS=%MINGW%\msys\1.0
  - cmd: set MINGW64=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0
  - cmd: set MSYS64=C:\msys64
  - cmd: set PATH=%MINGW%\bin;%MSYS%\bin;%PATH%
  #- cmd: set PATH=%MINGW64%\mingw32\bin;%MSYS64%\usr\bin;%PATH%
  - cmd: uname -a
  - cmd: echo %Platform%
  - cmd: sh.exe -c "echo $TEST_INTERVAL_LIB"
  # install libcppunit (from msys64)
  - cmd: C:\msys64\usr\bin\pacman.exe --noconfirm -S mingw32/mingw-w64-i686-cppunit
  - cmd: set CPATH=%CPATH%;C:\msys64\mingw32\include
  - cmd: set LIBRARY_PATH=%LIBRARY_PATH%;C:\msys64\mingw32\lib
  - cmd: set PREFIX=%HOMEDRIVE%%HOMEPATH%
  - cmd: sh.exe -c "echo $HOME"

build_script:
  - cmd: sh.exe -c "./waf configure --interval-lib=$TEST_INTERVAL_LIB --prefix=$PREFIX"
  - cmd: sh.exe -c "./waf build install clean"

test_script:
  - cmd: set PKG_CONFIG_PATH=%PREFIX%\share\pkgconfig
  # We need to add the path to libcppunit in PATH
  - cmd: set PATH=%PATH%;C:\msys64\mingw32\bin
  - cmd: sh.exe -c "echo $PKG_CONFIG_PATH"
  - cmd: sh.exe -c "ls -l $PKG_CONFIG_PATH"
  - cmd: sh.exe -c "./waf utest"

on_failure:
  - cmd: cat C:\projects\ibex-lib\__build__\config.log
  - cmd: cat C:\projects\ibex-lib\__build__\utest_config.log
  - cmd: cat C:\projects\ibex-lib\__build__\utest_run.log
